// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/db.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Types
type AddressCardKey_TYPE int32

const (
	AddressCardKey_NONE AddressCardKey_TYPE = 0
	AddressCardKey_DECK AddressCardKey_TYPE = 1
	AddressCardKey_CARD AddressCardKey_TYPE = 2
)

var AddressCardKey_TYPE_name = map[int32]string{
	0: "NONE",
	1: "DECK",
	2: "CARD",
}

var AddressCardKey_TYPE_value = map[string]int32{
	"NONE": 0,
	"DECK": 1,
	"CARD": 2,
}

func (x AddressCardKey_TYPE) String() string {
	return proto.EnumName(AddressCardKey_TYPE_name, int32(x))
}

func (AddressCardKey_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48c17124bb9d397f, []int{0, 0}
}

// Types for CardTransfer
type AddressCardKey_CARD_TYPE int32

const (
	AddressCardKey_EMPTY   AddressCardKey_CARD_TYPE = 0
	AddressCardKey_SEND    AddressCardKey_CARD_TYPE = 1
	AddressCardKey_RECEIVE AddressCardKey_CARD_TYPE = 2
	AddressCardKey_CREATE  AddressCardKey_CARD_TYPE = 3
)

var AddressCardKey_CARD_TYPE_name = map[int32]string{
	0: "EMPTY",
	1: "SEND",
	2: "RECEIVE",
	3: "CREATE",
}

var AddressCardKey_CARD_TYPE_value = map[string]int32{
	"EMPTY":   0,
	"SEND":    1,
	"RECEIVE": 2,
	"CREATE":  3,
}

func (x AddressCardKey_CARD_TYPE) String() string {
	return proto.EnumName(AddressCardKey_CARD_TYPE_name, int32(x))
}

func (AddressCardKey_CARD_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48c17124bb9d397f, []int{0, 1}
}

// Meta-data message for Address Key
type AddressCardKey struct {
	Type     int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	CardType int32 `protobuf:"varint,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	// Name for the registered asset
	DeckId string `protobuf:"bytes,3,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	// Block Height
	BlockHeight int32 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Transaction Index
	TxIndex int64 `protobuf:"varint,5,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	// Card Index
	CardIndex            int32    `protobuf:"varint,6,opt,name=card_index,json=cardIndex,proto3" json:"card_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressCardKey) Reset()         { *m = AddressCardKey{} }
func (m *AddressCardKey) String() string { return proto.CompactTextString(m) }
func (*AddressCardKey) ProtoMessage()    {}
func (*AddressCardKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_48c17124bb9d397f, []int{0}
}

func (m *AddressCardKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressCardKey.Unmarshal(m, b)
}
func (m *AddressCardKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressCardKey.Marshal(b, m, deterministic)
}
func (m *AddressCardKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressCardKey.Merge(m, src)
}
func (m *AddressCardKey) XXX_Size() int {
	return xxx_messageInfo_AddressCardKey.Size(m)
}
func (m *AddressCardKey) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressCardKey.DiscardUnknown(m)
}

var xxx_messageInfo_AddressCardKey proto.InternalMessageInfo

func (m *AddressCardKey) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AddressCardKey) GetCardType() int32 {
	if m != nil {
		return m.CardType
	}
	return 0
}

func (m *AddressCardKey) GetDeckId() string {
	if m != nil {
		return m.DeckId
	}
	return ""
}

func (m *AddressCardKey) GetBlockHeight() int32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *AddressCardKey) GetTxIndex() int64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *AddressCardKey) GetCardIndex() int32 {
	if m != nil {
		return m.CardIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("AddressCardKey_TYPE", AddressCardKey_TYPE_name, AddressCardKey_TYPE_value)
	proto.RegisterEnum("AddressCardKey_CARD_TYPE", AddressCardKey_CARD_TYPE_name, AddressCardKey_CARD_TYPE_value)
	proto.RegisterType((*AddressCardKey)(nil), "AddressCardKey")
}

func init() {
	proto.RegisterFile("protobuf/db.proto", fileDescriptor_48c17124bb9d397f)
}

var fileDescriptor_48c17124bb9d397f = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x7c, 0x67, 0x2a, 0xb2, 0xee, 0xc5, 0x88, 0x08, 0x31, 0x78, 0xc8, 0x49, 0x0f,
	0x9e, 0x3c, 0x86, 0x64, 0xc0, 0x50, 0x8c, 0x65, 0x0d, 0x42, 0x4f, 0xa1, 0xc9, 0xae, 0x36, 0x54,
	0x4c, 0x49, 0x23, 0xa4, 0xff, 0xc4, 0x9f, 0x2b, 0x3b, 0xbd, 0x3d, 0xf3, 0x3e, 0xf3, 0xb2, 0xcb,
	0xc0, 0xe5, 0x7e, 0x1c, 0xa6, 0xa1, 0xfd, 0xfd, 0x7c, 0x54, 0xed, 0x03, 0x71, 0xf2, 0x67, 0xc1,
	0x45, 0xa6, 0xd4, 0xa8, 0x0f, 0x87, 0x7c, 0x33, 0xaa, 0xa5, 0x3e, 0x0a, 0x01, 0xce, 0x74, 0xdc,
	0xeb, 0x88, 0xc5, 0x2c, 0x75, 0x25, 0xb1, 0xb8, 0x81, 0xb0, 0xdb, 0x8c, 0xaa, 0x21, 0x61, 0x91,
	0x08, 0x4c, 0x50, 0x1b, 0x79, 0x05, 0xbe, 0xd2, 0xdd, 0xae, 0xe9, 0x55, 0x64, 0xc7, 0x2c, 0x0d,
	0xa5, 0x67, 0xc6, 0x52, 0x89, 0x3b, 0x38, 0x6f, 0xbf, 0x87, 0x6e, 0xd7, 0x6c, 0x75, 0xff, 0xb5,
	0x9d, 0x22, 0x87, 0x8a, 0x0b, 0xca, 0x5e, 0x28, 0x12, 0xd7, 0x10, 0x4c, 0x73, 0xd3, 0xff, 0x28,
	0x3d, 0x47, 0x6e, 0xcc, 0x52, 0x5b, 0xfa, 0xd3, 0x5c, 0x9a, 0x51, 0xdc, 0x02, 0xd0, 0x9b, 0x27,
	0xe9, 0x51, 0x97, 0x7e, 0x41, 0x3a, 0xb9, 0x07, 0xa7, 0x5e, 0xaf, 0x50, 0x04, 0xe0, 0x54, 0x6f,
	0x15, 0xf2, 0x33, 0x43, 0x05, 0xe6, 0x4b, 0xce, 0x0c, 0xe5, 0x99, 0x2c, 0xb8, 0x95, 0x3c, 0x43,
	0x68, 0xa8, 0xa1, 0xd5, 0x10, 0x5c, 0x7c, 0x5d, 0xd5, 0xeb, 0xd3, 0xee, 0x3b, 0x56, 0x05, 0x67,
	0x62, 0x01, 0xbe, 0xc4, 0x1c, 0xcb, 0x0f, 0xe4, 0x96, 0x00, 0xf0, 0x72, 0x89, 0x59, 0x8d, 0xdc,
	0x6e, 0x3d, 0xba, 0xd0, 0xd3, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xfd, 0xf2, 0x71, 0x36,
	0x01, 0x00, 0x00,
}
