// Code generated by protoc-gen-go. DO NOT EDIT.
// source: utils/pa.protobuf

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protobuf package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protobuf package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the protobuf package

// Modes for asset issuance
type DeckSpawn_MODE int32

const (
	DeckSpawn_NONE        DeckSpawn_MODE = 0
	DeckSpawn_CUSTOM      DeckSpawn_MODE = 1
	DeckSpawn_ONCE        DeckSpawn_MODE = 2
	DeckSpawn_MULTI       DeckSpawn_MODE = 4
	DeckSpawn_MONO        DeckSpawn_MODE = 8
	DeckSpawn_UNFLUSHABLE DeckSpawn_MODE = 16
	// 0x20 used by SUBSCRIPTION (0x34 = 0x20 | 0x04 | 0x10)
	DeckSpawn_SUBSCRIPTION DeckSpawn_MODE = 52
	// Where X is the asset balance of the address.
	// This mode automatically enables MULTI & UNFLUSHABLE (0x34 = 0x20 | 0x04 | 0x10)
	// SINGLET is a combination of ONCE and MONO (0x02 | 0x08)
	DeckSpawn_SINGLET DeckSpawn_MODE = 10
)

var DeckSpawn_MODE_name = map[int32]string{
	0:  "NONE",
	1:  "CUSTOM",
	2:  "ONCE",
	4:  "MULTI",
	8:  "MONO",
	16: "UNFLUSHABLE",
	52: "SUBSCRIPTION",
	10: "SINGLET",
}

var DeckSpawn_MODE_value = map[string]int32{
	"NONE":         0,
	"CUSTOM":       1,
	"ONCE":         2,
	"MULTI":        4,
	"MONO":         8,
	"UNFLUSHABLE":  16,
	"SUBSCRIPTION": 52,
	"SINGLET":      10,
}

func (x DeckSpawn_MODE) String() string {
	return proto.EnumName(DeckSpawn_MODE_name, int32(x))
}

func (DeckSpawn_MODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_78c530c6cde2ff1f, []int{0, 0}
}

// Meta-data message for the deck spawn transaction
type DeckSpawn struct {
	// Protocol version number
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Name for the registered asset
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Number of decimals to define how much an asset can divided
	NumberOfDecimals uint32 `protobuf:"varint,3,opt,name=number_of_decimals,json=numberOfDecimals,proto3" json:"number_of_decimals,omitempty"`
	IssueMode        uint32 `protobuf:"varint,4,opt,name=issue_mode,json=issueMode,proto3" json:"issue_mode,omitempty"`
	// Free form asset specific data (optional)
	AssetSpecificData []byte `protobuf:"bytes,5,opt,name=asset_specific_data,json=assetSpecificData,proto3" json:"asset_specific_data,omitempty"`
	// card transaction fee (optional)
	// token amount to be burned upon each card transfer
	// to be encoded as: fee * 10**number_of_decimals
	// defaults to zero
	Fee                  uint32   `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeckSpawn) Reset()         { *m = DeckSpawn{} }
func (m *DeckSpawn) String() string { return proto.CompactTextString(m) }
func (*DeckSpawn) ProtoMessage()    {}
func (*DeckSpawn) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c530c6cde2ff1f, []int{0}
}

func (m *DeckSpawn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeckSpawn.Unmarshal(m, b)
}
func (m *DeckSpawn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeckSpawn.Marshal(b, m, deterministic)
}
func (m *DeckSpawn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeckSpawn.Merge(m, src)
}
func (m *DeckSpawn) XXX_Size() int {
	return xxx_messageInfo_DeckSpawn.Size(m)
}
func (m *DeckSpawn) XXX_DiscardUnknown() {
	xxx_messageInfo_DeckSpawn.DiscardUnknown(m)
}

var xxx_messageInfo_DeckSpawn proto.InternalMessageInfo

func (m *DeckSpawn) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DeckSpawn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeckSpawn) GetNumberOfDecimals() uint32 {
	if m != nil {
		return m.NumberOfDecimals
	}
	return 0
}

func (m *DeckSpawn) GetIssueMode() uint32 {
	if m != nil {
		return m.IssueMode
	}
	return 0
}

func (m *DeckSpawn) GetAssetSpecificData() []byte {
	if m != nil {
		return m.AssetSpecificData
	}
	return nil
}

func (m *DeckSpawn) GetFee() uint32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

// Transaction data for:
// - Card transfer transaction
// - Card issue transaction
// - Card burn transaction
type CardTransfer struct {
	// Protocol version number
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Amount to transfer
	Amount []uint64 `protobuf:"varint,2,rep,packed,name=amount,proto3" json:"amount,omitempty"`
	// Number of decimals
	// Should be equal to the number specified in the deck spawn transaction.
	// Encoded in this message for easy validation
	NumberOfDecimals uint32 `protobuf:"varint,3,opt,name=number_of_decimals,json=numberOfDecimals,proto3" json:"number_of_decimals,omitempty"`
	// Free form asset specific data (optional)
	AssetSpecificData    []byte   `protobuf:"bytes,4,opt,name=asset_specific_data,json=assetSpecificData,proto3" json:"asset_specific_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardTransfer) Reset()         { *m = CardTransfer{} }
func (m *CardTransfer) String() string { return proto.CompactTextString(m) }
func (*CardTransfer) ProtoMessage()    {}
func (*CardTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c530c6cde2ff1f, []int{1}
}

func (m *CardTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardTransfer.Unmarshal(m, b)
}
func (m *CardTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardTransfer.Marshal(b, m, deterministic)
}
func (m *CardTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardTransfer.Merge(m, src)
}
func (m *CardTransfer) XXX_Size() int {
	return xxx_messageInfo_CardTransfer.Size(m)
}
func (m *CardTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_CardTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_CardTransfer proto.InternalMessageInfo

func (m *CardTransfer) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CardTransfer) GetAmount() []uint64 {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *CardTransfer) GetNumberOfDecimals() uint32 {
	if m != nil {
		return m.NumberOfDecimals
	}
	return 0
}

func (m *CardTransfer) GetAssetSpecificData() []byte {
	if m != nil {
		return m.AssetSpecificData
	}
	return nil
}

func init() {
	proto.RegisterEnum("DeckSpawn_MODE", DeckSpawn_MODE_name, DeckSpawn_MODE_value)
	proto.RegisterType((*DeckSpawn)(nil), "DeckSpawn")
	proto.RegisterType((*CardTransfer)(nil), "CardTransfer")
}

func init() {
	proto.RegisterFile("utils/pa.protobuf", fileDescriptor_78c530c6cde2ff1f)
}

var fileDescriptor_78c530c6cde2ff1f = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4d, 0x4f, 0x83, 0x30,
	0x1c, 0xc6, 0x85, 0x31, 0x36, 0xfe, 0x9b, 0x5a, 0x6b, 0x62, 0x7a, 0x31, 0x21, 0x3b, 0x71, 0x30,
	0xf3, 0xa0, 0x5f, 0xc0, 0x01, 0x2a, 0x09, 0x50, 0xc3, 0xcb, 0x99, 0x74, 0x50, 0x12, 0xb2, 0xf1,
	0x12, 0x0a, 0xfa, 0x6d, 0xfc, 0x16, 0x7e, 0x3f, 0xb3, 0x3a, 0x8f, 0x33, 0xf1, 0xf6, 0x3c, 0xbf,
	0xa7, 0xed, 0xe1, 0x57, 0xb8, 0x18, 0x87, 0x6a, 0x2f, 0xee, 0x3b, 0xb6, 0xee, 0xfa, 0x76, 0x68,
	0x57, 0x5f, 0x2a, 0x18, 0x0e, 0xcf, 0x77, 0x71, 0xc7, 0x3e, 0x1a, 0x4c, 0x60, 0xf6, 0xce, 0x7b,
	0x51, 0xb5, 0x0d, 0x51, 0x4c, 0xc5, 0x3a, 0x8f, 0x7e, 0x2b, 0xc6, 0xa0, 0x35, 0xac, 0xe6, 0x44,
	0x35, 0x15, 0xcb, 0x88, 0x64, 0xc6, 0x77, 0x80, 0x9b, 0xb1, 0xde, 0xf2, 0x3e, 0x6b, 0xcb, 0xac,
	0xe0, 0x79, 0x55, 0xb3, 0xbd, 0x20, 0x13, 0x79, 0x11, 0xfd, 0x2c, 0xb4, 0x74, 0x8e, 0x1c, 0xdf,
	0x02, 0x54, 0x42, 0x8c, 0x3c, 0xab, 0xdb, 0x82, 0x13, 0x4d, 0x9e, 0x32, 0x24, 0x09, 0xda, 0x82,
	0xe3, 0x35, 0x5c, 0x33, 0x21, 0xf8, 0x90, 0x89, 0x8e, 0xe7, 0x55, 0x59, 0xe5, 0x59, 0xc1, 0x06,
	0x46, 0xa6, 0xa6, 0x62, 0x2d, 0xa3, 0x2b, 0x39, 0xc5, 0xc7, 0xc5, 0x61, 0x03, 0xc3, 0x08, 0x26,
	0x25, 0xe7, 0x44, 0x97, 0xef, 0x1c, 0xe2, 0x6a, 0x07, 0x5a, 0x40, 0x1d, 0x17, 0xcf, 0x41, 0x0b,
	0x69, 0xe8, 0xa2, 0x33, 0x0c, 0xa0, 0xdb, 0x69, 0x9c, 0xd0, 0x00, 0x29, 0x07, 0x4a, 0x43, 0xdb,
	0x45, 0x2a, 0x36, 0x60, 0x1a, 0xa4, 0x7e, 0xe2, 0x21, 0xed, 0x00, 0x03, 0x1a, 0x52, 0x34, 0xc7,
	0x97, 0xb0, 0x48, 0xc3, 0x67, 0x3f, 0x8d, 0x5f, 0x9f, 0x36, 0xbe, 0x8b, 0x10, 0x46, 0xb0, 0x8c,
	0xd3, 0x4d, 0x6c, 0x47, 0xde, 0x5b, 0xe2, 0xd1, 0x10, 0x3d, 0xe2, 0x05, 0xcc, 0x62, 0x2f, 0x7c,
	0xf1, 0xdd, 0x04, 0xc1, 0xea, 0x53, 0x81, 0xa5, 0xcd, 0xfa, 0x22, 0xe9, 0x59, 0x23, 0x4a, 0xde,
	0xff, 0xa1, 0xee, 0x06, 0x74, 0x56, 0xb7, 0x63, 0x33, 0x10, 0xd5, 0x9c, 0x58, 0x5a, 0x74, 0x6c,
	0xff, 0xd4, 0x77, 0xc2, 0x8f, 0x76, 0xc2, 0xcf, 0x56, 0x97, 0xff, 0xfb, 0xf0, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x7d, 0x06, 0x9a, 0xf4, 0xf1, 0x01, 0x00, 0x00,
}
